### ISSUE TITLE
Add a simple Django statistics module and remove google analytics 

### ISSUE THREAD

**Issue by ramibch** [ramiboutas/englishquiz#9]
https://pypi.org/project/django-request/

django-request is a statistics module for django. It stores requests in a database for admins to see, it can also be used to get statistics on who is online etc.

**Comment by ramiboutas** [comment]
django-request added. Not request info is loading... To be cheched!
![image](https://user-images.githubusercontent.com/33960822/221962647-00cbefca-4a60-4a18-b288-611cbe750bd9.png)

**Comment by ramiboutas** [comment]
TODO: try  collectstatic cmd

**Comment by ramiboutas** [comment]
it works now
